site_name: Django TypeScript
site_url: https://www.github.com
site_description: Django TypeScript

repo_url: https://github.com/peter-woyzbun/django-typescript
extra_css:
    - style.css
markdown_extensions:
 - toc:
    anchorlink: True

nav:
    - Home: index.md
    - Python: python.md

pages:
 - Home: 'index.md'
 - Python: 'python.md'
 - TypeScript: 'typescript.md'