site_name: Django TypeScript
site_url: https://www.github.com
site_description: Django TypeScript

repo_url: https://github.com/peter-woyzbun/django-typescript
extra_css:
    - style.css
markdown_extensions:
 - toc:
    anchorlink: True

pages:
 - Home: 'index.md'
 - Python:
    - 'Interface': 'python/interface.md'
    - 'Model Types': 'python/model-types.md'
    - 'Object Types': 'python/object-types.md'